### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by logileifs** [yaraht17/react-native-draggable-view#1]
This component doesn't work. It tries to look for a component Screen2 in `node_modules/components/` and fails with the error `Unable to resolve module` since I don't have that component

**Comment by yaraht17** [comment]
@logileifs Screen2 is example, you replace your components or see example for that 
https://github.com/yaraht17/react-native-draggable-view/tree/master/example/CartView/app/components
You put your code in screen2 or rename it

**Comment by logileifs** [comment]
I did not have any component called screen2. I had my own component with a different name but the draggable-view was still trying to import a component called screen2 somewhere and fails because it can not find it

**Comment by yaraht17** [comment]
@logileifs it's my bad, i import Screen2 to index.js, you remove line 17 in index.js and now can work. 
Or you reinstall module, i have update it

**Comment by danish4114** [comment]
@logileifs ,Screen2 is not any liabrary component,its only for example overthere,You have to use liabrary component like View,Text etc instead of.
