### ISSUE TITLE
Not able to run Example

### ISSUE THREAD

**Issue by CrazzzyDev** [yaraht17/react-native-draggable-view#2]
When I tried the Drawer, it gives below error on device.
What could be the reason?

Initializing <RCTCxxBridge: 0x6000001a71c0> (parent: <RCTBridge: 0x6080000a37e0>, executor: RCTWebSocketExecutor)
2017-08-24 01:44:21.955 [fatal][tid:main] Unable to resolve module `ReactNativeART` from `<user DIR path>/Example/DemoDrawer/node_modules/react-native/Libraries/react-native/react-native-implementation.js`: Module does not exist in the module map

**Comment by yaraht17** [comment]
Look error path, it's not a error of my module. Please check react native version. You can try reinstall node_module: 
rm -rf node_module 
npm install

**Comment by CrazzzyDev** [comment]
"dependencies": {
		"native-base": "^2.3.1",
		"react": "16.0.0-alpha.12",
		"react-native": "0.47.2",
		"react-native-draggable-drawer": "0.0.8",
		"react-native-draggable-view": "0.0.4"
	},

I tired remove and reinstall node_module. it doesn't work.
If noticed, If I remove this 'react-native-draggable-view' package and try to run app it runs successfully. It gives me this error with the draggable package.

**Comment by yaraht17** [comment]
Do you try with my example? https://github.com/yaraht17/react-native-draggable-view/tree/master/example/CartView
remove 'react-native-draggable-drawer' from package.json
Try it! Long time, i don't check it, but i think it working? Now, i very busy, don't support for you. Maybe next month i free, i can help you! 
Thank

**Comment by ChelseaDan** [comment]
Hi yayaht17! Thanks for the awesome lib! Took me a bit of work to get it working but it's all good now.

**Comment by ChelseaDan** [comment]
I'm not sure if you have a work around for this, but when I drag the window to the top, the iphone then gets confused between you trying to put it back down or the notifications? And usually thinks you want the notifications. The outcome is therefore that once it's up at the top, you can't pull it down again! At least not on the simulator but maybe it'll be different on the actual device. Will let you know. Thanks again!

**Comment by yaraht17** [comment]
@ChelseaDan I know it, but i don't work with this module now, if you have a solution, you can create PR! Thanks.

**Comment by ChelseaDan** [comment]
No worries. TY
