### ISSUE TITLE
slide up programmatically 

### ISSUE THREAD

**Issue by edxe** [yaraht17/react-native-draggable-view#3]
is there any way to invoke the slide up animation programmatically?

**Comment by yaraht17** [comment]
Now, i don't support it, you can create pull request.

**Comment by koswarabilly** [comment]
@edxe i have a simple approach, I know that this is not the best solution.

go to the library `index.js`

add this method 
```
open() {
    this.startAnimation(-100, 500, this.state.initialPositon, null, this.state.finalPosition);
    this.props.onRelease && this.props.onRelease(true); // only add this line if you need to detect if the drawer is up or not
 }
```

then add ref in your drawer calling component:
```
<Drawer 
          ref={(c) => {
            this._drawerRef = c
          }}
          ...
```

then you can call the open function by using the ref:

```
openTheDrawer() {
    this._drawerRef.open()
}
```

there you are the drawer will open like you usually do.

Remember this is a alternate approach and it is not the best obviously but it is better than nothing :)

**Comment by yaraht17** [comment]
Updated from PR!
