### ISSUE TITLE
import Drawrer throwing an error

### ISSUE THREAD

**Issue by Leon31** [yaraht17/react-native-draggable-view#4]
As I try to import Drawer from 'react-native-draggable-view' I got this error: undefined is not a function (near '..._react2.default.createClass...').
I installed react-native-draggable-view with npm i react-native-draggable-view --save and my package.json shows the version 0.0.4

Am I doing something wrong? Do you know which might be the problem?

**Comment by yaraht17** [comment]
You can show me error detail? Image cature or check in your node_module has react-native-draggable-view.

**Comment by faketon** [comment]
How to sovled this ?
